### PR TITLE
Added PUT /users/:usernameOrEmail/email separately 

### PR DESCRIPTION
**Pull request by SerenModz21**

### CODE REVIEW

**Comment by fahimmehraj** [comment]
/user/:user/email isn't a valid route.

**Comment by SerenModz21** [comment]
the findNameOrEmail function for it is in #29 and works fine with that function

**Comment by SerenModz21** [comment]
this2 was a username for one of the documents when testing and it worked perfectly fine

image

**Comment by fahimmehraj** [comment]
i understand i tested it myself as well, but the route name needs to be changed according to the README

**Comment by SerenModz21** [comment]
its exactly the same as what the readme says now `PUT /users/:usernameOrEmail/email`

**Pull request merged**
